name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.11'

  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  docker:
    # needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-fastapi-app:${{ steps.docker_tags.outputs.tags }}

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     platforms: linux/amd64,linux/arm64/v8
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-fastapi-app:latest  # Укажите имя образа

  # deploy:
  #   needs: docker
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: SSH Deploy
  #       uses: appleboy/ssh-action@v0.1.7
  #       with:
  #         host: ${{ secrets.DEPLOY_HOST_IMMERS }}
  #         username: ${{ secrets.DEPLOY_USER }}
  #         key: ${{ secrets.DEPLOY_KEY }}
  #         port: ${{ secrets.DEPLOY_PORT }}
  #         script: |
  #           docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-fastapi-app:latest
  #           docker stop my-fastapi-app || true
  #           docker rm my-fastapi-app || true
  #           docker run -d -p 8000:8000 --name my-fastapi-app ${{ secrets.DOCKERHUB_USERNAME }}/my-fastapi-app:latest
